# Generated by Django 6.0.4 on 2026-04-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('country', models.CharField(max_length=100)),
                ('country_code_2', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='Code (Two Character)')),
                ('country_code_3', models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True, verbose_name='Code (Three Character)')),
                ('country_number_code', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Country Number Code')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ('country',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('region_code', models.CharField(db_index=True, max_length=10, verbose_name='Region Code')),
                ('region', models.CharField(max_length=100)),
                ('primary_level', models.CharField(blank=True, max_length=50, null=True, verbose_name='Primary Level')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.country')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('region', 'region_code'),
                'unique_together': {('country', 'region')},
            },
        ),
    ]
