# Generated by Django 6.0.4 on 2026-04-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
