# Generated by Django 3.0.6 on 2020-08-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200802_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.SmallIntegerField(choices=[(0, 'PROJECT_USER'), (1, 'PROJECT_OWNER'), (2, 'PROJECT_MANAGER')], default=0, help_text='The role of the user.', verbose_name='Role'),
        ),
    ]
