# Generated by Django 3.2.3 on 2021-05-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200806_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventorytype',
            name='public_id',
            field=models.CharField(blank=True, help_text='Public ID that identifies an individual inventory type.', max_length=30, unique=True, verbose_name='Public Inventory Type ID'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
