# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 00:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inventory.common.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(help_text='The date and time of creation.', verbose_name='Date Created')),
                ('updated', models.DateTimeField(help_text='The date and time last updated.', verbose_name='Last Updated')),
                ('active', models.BooleanField(default=True, help_text='If checked the record is active.', verbose_name='Active')),
                ('public_id', models.CharField(blank=True, help_text='Public ID to identify a individual supplier.', max_length=30, unique=True, verbose_name='Public Supplier ID')),
                ('name', models.CharField(help_text='The name of the supplier.', max_length=250, verbose_name='Name')),
                ('address_01', models.CharField(blank=True, help_text='Address line one.', max_length=50, null=True, verbose_name='Address 1')),
                ('address_02', models.CharField(blank=True, help_text='Address line two.', max_length=50, null=True, verbose_name='Address 2')),
                ('city', models.CharField(blank=True, help_text='The city of the supplier.', max_length=30, null=True, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, help_text='The postal code in the country.', max_length=15, null=True, verbose_name='Postal Code')),
                ('phone', models.CharField(blank=True, help_text='The phone number of the supplier.', max_length=20, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, help_text='The fax number of the supplier', max_length=20, null=True, verbose_name='FAX')),
                ('email', models.EmailField(blank=True, help_text='The email of the supplier.', max_length=254, null=True, verbose_name='Email')),
                ('url', models.URLField(blank=True, help_text='The web site of the supplier.', null=True, verbose_name='URL')),
                ('stype', models.SmallIntegerField(choices=[(0, 'MFG & Dist'), (1, 'Manufacturer'), (2, 'Distributor')], help_text='The type of supplier.', verbose_name='Supplier Type')),
                ('country', models.ForeignKey(blank=True, help_text='The country.', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.Country', verbose_name='Country')),
                ('creator', models.ForeignKey(editable=False, help_text='The user who created this record.', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_supplier_creator_related', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('language', models.ForeignKey(blank=True, help_text='The language code.', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.Language', verbose_name='Language')),
                ('project', models.ForeignKey(db_index=False, help_text='The project that owns this record.', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='projects.Project', verbose_name='Project')),
                ('subdivision', models.ForeignKey(blank=True, help_text='The subdivision in the country.', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.Subdivision', verbose_name='State/Province')),
                ('timezone', models.ForeignKey(blank=True, help_text='The timezone.', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.TimeZone', verbose_name='Timezone')),
                ('updater', models.ForeignKey(editable=False, help_text='The last user to update this record.', on_delete=django.db.models.deletion.CASCADE, related_name='suppliers_supplier_updater_related', to=settings.AUTH_USER_MODEL, verbose_name='Updater')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name',),
                'verbose_name': 'Supplier',
            },
            bases=(inventory.common.model_mixins.ValidateOnSaveMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set([('project', 'name')]),
        ),
    ]
