# Generated by Django 3.0.6 on 2020-08-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200802_1205'),
        ('accounts', '0003_auto_20180505_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project_default',
            field=models.ForeignKey(blank=True, help_text='The default project public_id.', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='Project Default'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='_role',
        ),
    ]
