# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 04:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20151130_0059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('question__question',), 'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('question',), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='user',
            name='project_default',
            field=models.SmallIntegerField(choices=[(0, 'Last Project Used'), (1, 'Always Choose Project')], default=0, verbose_name='Project Default'),
        ),
        migrations.AlterField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='owners', to='accounts.Answer', verbose_name='Answers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='owners', to='projects.Project', verbose_name='Projects'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username'),
        ),
    ]
