# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 18:46
from __future__ import unicode_literals

import django.contrib.auth.validators
from django.db import migrations, models
import inventory.common.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20151224_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, storage=inventory.common.storage.InventoryFileStorage(), upload_to='user_photos', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
