# Used in development only on my home server.
WSGIRestrictStdin On
WSGIRestrictStdout On
LoadModule wsgi_module "/home/cnobile/.virtualenvs/old-inv/lib/python3.13/site-packages/mod_wsgi/server/mod_wsgi-py313.cpython-313-x86_64-linux-gnu.so"
WSGIPythonHome "/usr"
ServerName nemesis

<VirtualHost *:80>
  ServerName inventory.homelinux.org
  ServerAlias www.inventory.homelinux.org
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>

<VirtualHost _default_:443>
  ServerName inventory.homelinux.org
  ServerAlias www.inventory.homelinux.org
  ServerAdmin carl.nobile@gmail.com
  # Possible values include: debug, info, notice, warn, error, crit,
  #                          alert, emerg.
  LogLevel warn
  ErrorLog ${APACHE_LOG_DIR}/inventory-error.log
  CustomLog ${APACHE_LOG_DIR}/inventory-access.log combined

  # Activate virtualenv
  WSGIDaemonProcess inventory display-name=%{GROUP} user=cnobile \
    group=cnobile processes=5 threads=10 python-eggs=/tmp \
    python-home=/home/cnobile/.virtualenvs/old-inv \
    python-path=/home/cnobile/inventory

  WSGIProcessGroup inventory
  WSGIScriptAlias / /home/cnobile/inventory/apache/app.wsgi

  <Directory /home/cnobile/inventory/apache>
    Require all granted
  </Directory>

  # Static files
  Alias /static /home/cnobile/inventory/inventory/static
  <Directory /home/cnobile/inventory/inventory/static>
    Require all granted
  </Directory>

  Alias /favicon.ico /home/cnobile/inventory/inventory/static/img/favicon.ico

  Alias /docs/ /home/cnobile/inventory/docs/api/
  <Directory /home/cnobile/inventory/docs/api/>
    Require all granted
  </Directory>

  SSLEngine on
  SSLCertificateFile /etc/ssl/certs/inventory.pem
  SSLCertificateKeyFile /etc/ssl/private/inventory.pem
</VirtualHost>
