WSGIRestrictStdin On
WSGIRestrictStdout On
LoadModule wsgi_module "/opt/inventory/.virtualenvs/inventory/lib/python3.12/site-packages/mod_wsgi/server/mod_wsgi-py312.cpython-312-x86_64-linux-gnu.so"

<VirtualHost *:80>
  ServerName inventory.tetrasys-design.net
  ServerAlias www.inventory.tetrasys-design.net
  RewriteEngine On
  RewriteCond %{HTTPS} off
  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
</VirtualHost>

<VirtualHost _default_:443>
  ServerName inventory.tetrasys-design.net
  ServerAlias www.inventory.tetrasys-design.net
  ServerAdmin carl.nobile@gmail.com
  RequestHeader set X-Forwarded-Proto "https"
  # Possible values include: debug, info, notice, warn, error, crit,
  #                          alert, emerg.
  LogLevel warn
  ErrorLog ${APACHE_LOG_DIR}/inventory-error.log
  CustomLog ${APACHE_LOG_DIR}/inventory-access.log combined

  # Activate virtualenv
  WSGIDaemonProcess inventory display-name=%{GROUP} user=inventory \
      group=inventory processes=5 threads=10 python-eggs=/tmp \
      python-home=/opt/inventory/.virtualenvs/inventory \
      python-path=/opt/inventory/inventory

  WSGIProcessGroup inventory
  WSGIScriptAlias / /opt/inventory/inventory/apache/app.wsgi

  <Directory /opt/inventory/inventory/apache>
      Require all granted
  </Directory>

  # Static files
  Alias /static /opt/inventory/inventory/inventory/static
  <Directory /opt/inventory/inventory/inventory/static>
    Require all granted
  </Directory>

  Alias /favicon.ico /opt/inventory/inventory/inventory/static/img/favicon.ico

  Alias /docs/ /opt/inventory/inventory/docs/api/
  <Directory /opt/inventory/inventory/docs/api/>
    Require all granted
  </Directory>

  SSLEngine on
  Include /etc/letsencrypt/options-ssl-apache.conf
  SSLCertificateFile /etc/letsencrypt/live/inventory.tetrasys-design.net-0001/fullchain.pem
  SSLCertificateKeyFile /etc/letsencrypt/live/inventory.tetrasys-design.net-0001/privkey.pem
</VirtualHost>
