# Generated by Django 6.0.4 on 2026-04-21 17:43

import django.db.models.deletion
import inventory.apps.utils.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCodeDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('segment_length', models.PositiveIntegerField(editable=False, verbose_name='Segment Length')),
                ('segment_separator', models.CharField(default=':', editable=False, help_text='The separator to use between segments. Separators are hard coded as a colon (:).', max_length=3, verbose_name='Segment Separator')),
                ('char_definition', models.CharField(db_index=True, help_text="Determine the character position definition where alpha='\\a', numeric='\\d', punctuation='\\p', or any char='any char'. ex. \\a\\d\\d\\d could be B001 or \\a@\\d\\d could be D@99", max_length=248, verbose_name='Character Definition')),
                ('segment_order', models.PositiveIntegerField(default=0, help_text='A number indicating the order that this segment will appear in the location code. Numbers should start with 0 (Can be editied in the list view also).', verbose_name='Segment Order')),
                ('description', inventory.apps.utils.modelfields.SizableCharField(default='', help_text='Enter a description of the catageory segments.', max_length=1024, verbose_name='Description')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Code Default',
                'verbose_name_plural': 'Location Code Defaults',
                'ordering': ('segment_order',),
            },
        ),
        migrations.CreateModel(
            name='LocationCodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('mtime', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(db_index=True, help_text='See the LocationCodeDefault.description for the format used.', max_length=248)),
                ('path', models.CharField(editable=False, max_length=248)),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='maintenance.locationcodecategory')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('char_definition', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='maintenance.locationcodedefault')),
            ],
            options={
                'verbose_name': 'Location Code',
                'verbose_name_plural': 'Location Codes',
                'ordering': ('path',),
            },
        ),
    ]
