# Generated by Django 2.0.5 on 2018-05-05 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='The manufacturer that produced the item.', limit_choices_to={'stype__in': [1, 0]}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers_items', to='suppliers.Supplier', verbose_name='Manufacturer'),
        ),
    ]
