# Generated by Django 3.0.6 on 2020-08-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20180505_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='process',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, help_text="If 'Yes' an inventory item is created from the invoice.", verbose_name='Create Item'),
        ),
    ]
